version: "3.8"

services:
  # 1. API Gateway (The "Door" for your AWS Server)
  nginx_gateway:
    image: nginx:latest
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      # Iska path sahi hona chahiye server par
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
    networks:
      - foodapp-network

  # 2. Your C++ User Service (The "Brain")
  user-service:
    build: ./foodapp-backend
    container_name: cpp_user_service
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./ssl:/app/certificates:ro
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=foodapp
      - KAFKA_CA_PATH=/app/certificates/ca.pem
      - KAFKA_CERT_PATH=/app/certificates/service.cert
      - KAFKA_KEY_PATH=/app/certificates/service.key
    depends_on:
      - db
    networks:
      - foodapp-network

  # 3. Your Local Database (The "Storage")
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=foodapp
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - foodapp-network

networks:
  foodapp-network:
    driver: bridge

volumes:
  mysql_data:
