events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # 1. This serves your "Swiggy" HTML/CSS/JS
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # 2. This routes the "Sign Up" data to your C++ Backend
        location /api/register {
            proxy_pass http://user_service:8080; 
            proxy_set_header Host $host;
            add_header 'Access-Control-Allow-Origin' '*';
        }
    }
}